name: Azure Naija CI

on:

# when there is a commit to our master 
    push:
        branches: main

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -
                name: Docker Login
                uses: docker/login-action@v3
                with:
                    username: ${{ vars.DOKCER_USERNAME }}
                    password: ${{ secrets.DOCKER_TOKEN }}

            - 
                name: Docker Login
                uses: docker/build-push-action@v5
                with:
                    dockerfile: Dockerfile
                    context: .
                    push: true
                    tags: blueninjas/planet:latest


                    

